import React, { useState, useEffect } from 'react';
import { BrainCircuit, AlertTriangle, PenTool, Clock, ShieldAlert, Wrench, Search, ChevronRight } from 'lucide-react';
import api from '../services/api';

const AISuggestions = () => {
  const [incidents, setIncidents] = useState([]);
  const [selectedIncident, setSelectedIncident] = useState(null);
  const [aiAnalysis, setAiAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchIncidents = async () => {
      try {
        const response = await api.get('/incidents');
        setIncidents(response.data.data || []);
      } catch (err) {
        // Fallback mock incidents if API fails or no data
        setIncidents([
          { id: 'INC-101', transformerId: 'T001', type: 'Wire Break', status: 'Open', polesAffected: 15, timestamp: new Date().toISOString() },
          { id: 'INC-102', transformerId: 'T002', type: 'Transformer Overload', status: 'Open', polesAffected: 30, timestamp: new Date(Date.now() - 3600000).toISOString() }
        ]);
      }
    };
    fetchIncidents();
  }, []);

  const analyzeIncident = async (incident) => {
    setSelectedIncident(incident);
    setLoading(true);
    setError(null);
    setAiAnalysis(null);

    try {
      const response = await api.post('/ai/suggestions', { incidentData: incident });
      setAiAnalysis(response.data.data);
    } catch (err) {
      setError('Failed to generate AI analysis. Please check your API configuration.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 h-full flex flex-col">
      <div className="flex items-center space-x-3 text-primary mb-2">
        <BrainCircuit size={28} />
        <h2 className="text-2xl font-bold tracking-tight">AI Insights & Analytics</h2>
      </div>

      <div className="flex flex-col lg:flex-row gap-6 flex-1 min-h-0">
        
        {/* Incident List */}
        <div className="w-full lg:w-1/3 bg-card border border-border rounded-xl shadow-soft flex flex-col">
          <div className="p-4 border-b border-border bg-background rounded-t-xl">
            <h3 className="font-semibold text-textmain flex items-center">
              <AlertTriangle className="mr-2 text-warning" size={18} />
              Pending Incidents
            </h3>
          </div>
          <div className="flex-1 overflow-y-auto p-2 space-y-2">
            {incidents.map(inc => (
              <div 
                key={inc.id}
                onClick={() => analyzeIncident(inc)}
                className={`p-4 rounded-lg border cursor-pointer transition-all ${selectedIncident?.id === inc.id ? 'border-primary bg-primary/5 shadow-sm' : 'border-border hover:border-primary/30 hover:bg-gray-50'}`}
              >
                <div className="flex justify-between items-start mb-2">
                  <span className="font-bold text-textmain">{inc.id}</span>
                  <span className="text-xs bg-red-100 text-danger px-2 py-0.5 rounded-full font-semibold">{inc.type}</span>
                </div>
                <div className="text-sm text-secondary flex justify-between">
                  <span>Trans: {inc.transformerId}</span>
                  <span className="flex items-center text-primary font-medium text-xs">
                    Analyze <ChevronRight size={14} className="ml-1" />
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Analysis Panel */}
        <div className="w-full lg:w-2/3 bg-card border border-border rounded-xl shadow-soft flex flex-col">
          {loading ? (
            <div className="flex-1 flex flex-col items-center justify-center text-primary space-y-4">
              <BrainCircuit className="animate-pulse" size={48} />
              <p className="font-semibold text-lg">Analyzing incident data with AI...</p>
            </div>
          ) : error ? (
            <div className="flex-1 flex flex-col items-center justify-center text-danger p-8">
              <AlertTriangle size={48} className="mb-4" />
              <p className="font-bold text-lg">{error}</p>
            </div>
          ) : aiAnalysis ? (
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              
              <div className="flex items-start justify-between border-b border-border pb-4">
                <div>
                  <h3 className="text-xl font-bold text-textmain mb-1">Analysis for {selectedIncident.id}</h3>
                  <p className="text-sm text-secondary">Generated by Gemini AI Model</p>
                </div>
                <span className="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm font-bold flex items-center">
                  <Clock size={16} className="mr-2" />
                  ETA: {aiAnalysis.estimatedRestorationTime}
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                <div className="bg-background rounded-xl p-5 border border-border">
                  <h4 className="flex items-center font-bold text-primary mb-3">
                    <Search size={18} className="mr-2" /> Root Cause
                  </h4>
                  <p className="text-sm text-textmain leading-relaxed">{aiAnalysis.rootCause}</p>
                </div>

                <div className="bg-background rounded-xl p-5 border border-border">
                  <h4 className="flex items-center font-bold text-primary mb-3">
                    <BrainCircuit size={18} className="mr-2" /> Reasoning
                  </h4>
                  <p className="text-sm text-textmain leading-relaxed">{aiAnalysis.reasoning}</p>
                </div>

                <div className="bg-background rounded-xl p-5 border border-border md:col-span-2">
                  <h4 className="flex items-center font-bold text-primary mb-3">
                    <PenTool size={18} className="mr-2" /> Crew Recommendation
                  </h4>
                  <p className="text-sm text-textmain leading-relaxed">{aiAnalysis.crewRecommendation}</p>
                </div>

                <div className="bg-red-50 rounded-xl p-5 border border-red-100">
                  <h4 className="flex items-center font-bold text-danger mb-3">
                    <ShieldAlert size={18} className="mr-2" /> Safety Precautions
                  </h4>
                  <ul className="list-disc pl-5 text-sm text-red-900 space-y-1">
                    {aiAnalysis.safetyPrecautions?.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className="bg-blue-50 rounded-xl p-5 border border-blue-100">
                  <h4 className="flex items-center font-bold text-primary mb-3">
                    <Wrench size={18} className="mr-2" /> Preventive Maintenance
                  </h4>
                  <ul className="list-disc pl-5 text-sm text-blue-900 space-y-1">
                    {aiAnalysis.preventiveMaintenance?.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>

              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-secondary">
              <BrainCircuit size={64} className="opacity-20 mb-4" />
              <p className="font-medium text-lg">Select an incident to generate AI insights</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AISuggestions;
